### ISSUE TITLE
CRITICAL:root:Mismatch with AAR names! Order of the AARs must match!

### ISSUE THREAD

**Issue by jon-xu** [tare/Splotch#1]
Hello,

I am using SPLOTCH to analyse a set of ST data and I got this error when I tried to generate input files, could you please help to advise how I can get it correct? Appreciations!

[metadata.txt](https://github.com/tare/Splotch/files/3913978/metadata.txt)
[Brain1_ctrl_dt_tissue.tsv_splotch.unified.txt](https://github.com/tare/Splotch/files/3913983/Brain1_ctrl_dt_tissue.tsv_splotch.unified.txt)
[Brain1_ctrl_dt_tissue.tsv_splotch_annot.txt](https://github.com/tare/Splotch/files/3913984/Brain1_ctrl_dt_tissue.tsv_splotch_annot.txt)

$ splotch_generate_input_files -c *.unified.tsv -m metadata.tsv -s 2389.0 -l 3 -o data_three
INFO:root:Reading metadata
INFO:root:Initializing
INFO:root:beta_level_1[1] := Brain1
INFO:root:beta_level_2[1] := Brain1 ctrl
INFO:root:beta_level_3[1] := Brain1 ctrl dt
INFO:root:beta_level_3[2] := Brain1 ctrl hp
INFO:root:beta_level_2[2] := Brain1 treated
INFO:root:beta_level_3[3] := Brain1 treated dt
INFO:root:beta_level_3[4] := Brain1 treated hp
INFO:root:beta_level_1[2] := Brain2
INFO:root:beta_level_2[3] := Brain2 ctrl
INFO:root:beta_level_3[5] := Brain2 ctrl dt
INFO:root:beta_level_3[6] := Brain2 ctrl hp
INFO:root:beta_level_2[4] := Brain2 treated
INFO:root:beta_level_3[7] := Brain2 treated dt
INFO:root:beta_level_3[8] := Brain2 treated hp
INFO:root:beta_level_1[3] := Brain3
INFO:root:beta_level_2[5] := Brain3 ctrl
INFO:root:beta_level_3[9] := Brain3 ctrl dt
INFO:root:beta_level_3[10] := Brain3 ctrl hp
INFO:root:beta_level_2[6] := Brain3 treated
INFO:root:beta_level_3[11] := Brain3 treated dt
INFO:root:beta_level_3[12] := Brain3 treated hp
INFO:root:beta_level_1[4] := Brain4
INFO:root:beta_level_2[7] := Brain4 ctrl
INFO:root:beta_level_3[13] := Brain4 ctrl dt
INFO:root:beta_level_3[14] := Brain4 ctrl hp
INFO:root:beta_level_2[8] := Brain4 treated
INFO:root:beta_level_3[15] := Brain4 treated dt
INFO:root:beta_level_3[16] := Brain4 treated hp
INFO:root:beta_level_1[5] := Brain5
INFO:root:beta_level_2[9] := Brain5 ctrl
INFO:root:beta_level_3[17] := Brain5 ctrl dt
INFO:root:beta_level_3[18] := Brain5 ctrl hp
INFO:root:beta_level_2[10] := Brain5 treated
INFO:root:beta_level_3[19] := Brain5 treated dt
INFO:root:beta_level_3[20] := Brain5 treated hp
INFO:root:beta_level_1[6] := Brain6
INFO:root:beta_level_2[11] := Brain6 ctrl
INFO:root:beta_level_3[21] := Brain6 ctrl dt
INFO:root:beta_level_3[22] := Brain6 ctrl hp
INFO:root:beta_level_2[12] := Brain6 treated
INFO:root:beta_level_3[23] := Brain6 treated dt
INFO:root:beta_level_3[24] := Brain6 treated hp
INFO:root:Processing Brain1_ctrl_dt_tissue.tsv_splotch.unified.tsv
INFO:root:Reading data
INFO:root:Detecting tissue sections on the array
INFO:root:Found 2 candidate tissue sections
INFO:root:Keeping 1 tissue sections
INFO:root:Processing Brain1_ctrl_hp_tissue.tsv_splotch.unified.tsv
INFO:root:Reading data
CRITICAL:root:Mismatch with AAR names! Order of the AARs must match!

**Comment by tare** [comment]
Hi,

Based on the error message it looks like the row names differ in the files Brain1_ctrl_dt_tissue.tsv_splotch_annot and Brain1_ctrl_hp_tissue.tsv_splotch_annot. Please make sure that the row names are identical across the annotation files.

Tarmo

**Comment by jon-xu** [comment]
That works, thanks!
