### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by Dillon214** [tare/Splotch#5]
Hello Splotch developers,

I found Splotch while exploring a couple publications centering around spatial transcriptomics and think it could be very useful in analyzing a spatial dataset I'm working on. However, I'm running into issues during the installation process, which I'll go into below. 

After running 'pip install git+https://git@github.com/tare/Splotch.git' I tested out the commands detailed in the installation tutorial and found no issues with the commands 'splotch' and 'splotch_prepare_count_files', however when running the command 'splotch_generate_input_files', I get an error. See 'ERROR 1' below for the full error message. 

That is the first of the issues I encountered. The next issue I encountered was with the second installation command 'pip install --no-deps --force-reinstall --upgrade --install-option="--stan" git+https://git@github.com/tare/Splotch.git'

Installation does not finish, and I get another error. See 'ERROR 2' below for the full error message. 

Do you have any advice for how I can avoid these errors and start using Splotch? I would be very grateful for a timely response. 

----------------------
ERROR 1:

Traceback (most recent call last):
  File "/home/users/browneld/miniconda3/bin/splotch_generate_input_files", line 18, in <module>
    from splotch.utils import get_variable_mappings, watershed_tissue_sections, \
  File "/home/users/browneld/miniconda3/lib/python3.9/site-packages/splotch/utils.py", line 15, in <module>
    from skimage.morphology import watershed
ImportError: cannot import name 'watershed' from 'skimage.morphology' (unknown location)

----------------------
ERROR 2: 

WARNING: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
Collecting git+https://****@github.com/tare/Splotch.git
  Cloning https://****@github.com/tare/Splotch.git to /tmp/pip-req-build-01clj5se
  Running command git clone --quiet 'https://****@github.com/tare/Splotch.git' /tmp/pip-req-build-01clj5se
  Resolved https://****@github.com/tare/Splotch.git to commit 1c95a24ee20226924ad0508eb09f299542cc42b3
  Preparing metadata (setup.py) ... done
Skipping wheel build for Splotch, due to binaries being disabled for it.
Installing collected packages: Splotch
  Running setup.py install for Splotch ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Splotch did not run successfully.
  │ exit code: 3
  ╰─> [26 lines of output]
      running install
      /home/users/browneld/miniconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/splotch
      copying splotch/__init__.py -> build/lib/splotch
      copying splotch/utils.py -> build/lib/splotch
      running build_scripts
      creating build/scripts-3.9
      copying and adjusting bin/splotch_prepare_count_files -> build/scripts-3.9
      copying and adjusting bin/splotch_generate_input_files -> build/scripts-3.9
      copying bin/splotch -> build/scripts-3.9
      changing mode of build/scripts-3.9/splotch_prepare_count_files from 644 to 755
      changing mode of build/scripts-3.9/splotch_generate_input_files from 644 to 755
      changing mode of build/scripts-3.9/splotch from 644 to 755
      running install_lib
      creating /home/users/browneld/miniconda3/lib/python3.9/site-packages/splotch
      copying build/lib/splotch/__init__.py -> /home/users/browneld/miniconda3/lib/python3.9/site-packages/splotch
      copying build/lib/splotch/utils.py -> /home/users/browneld/miniconda3/lib/python3.9/site-packages/splotch
      byte-compiling /home/users/browneld/miniconda3/lib/python3.9/site-packages/splotch/__init__.py to __init__.cpython-39.pyc
      byte-compiling /home/users/browneld/miniconda3/lib/python3.9/site-packages/splotch/utils.py to utils.cpython-39.pyc
      running install_data
      stan/lib/stan_math/make/libraries:117: *** "Need to set TBB_CXX_TYPE for non-standard compiler other than gcc or clang.".  Stop.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Splotch

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by tare** [comment]
Hi Dillon, 

Thank you for your interest.

Error 1: It seems that watershed has been moved from `skimage.morphology` to `skimage.segmentation`. As a quick fix, please install an older version of scikit-image (e.g. 0.17 or maybe 0.18). As a proper fix, I should either pin the version or update the import.

Error 2: My guess is that you don't have a working compiler toolchain. Can you please see if you're able to run the following commands to download and compile CmdStan:
```console
wget https://github.com/stan-dev/cmdstan/releases/download/v2.31.0/cmdstan-2.31.0.tar.gz
tar -xvzf cmdstan-2.31.0.tar.gz
cd cmdstan-2.31.0
make build -j4
```
To test CmdStan, you can run
```console
make examples/bernoulli/bernoulli
```
If this works, then you should be able to use the second installation method.

**Comment by tare** [comment]
I have made the necessary changes to address the updated external packages. I was able to run the code successfully. Please try the code before I merge it to the master branch. You should be able to install the version from the dev branch by running the following commands:
```console
$ pip install git+https://git@github.com/tare/Splotch.git@dev
$ pip install --no-deps --force-reinstall --upgrade --install-option="--stan" git+https://git@github.com/tare/Splotch.git@dev
```

**Comment by Dillon214** [comment]
Hi tare,

Thank you so much for the speedy responses! I will give the new changes a whirl as soon as I am able to, and thanks again for the assistance. I'll update with my progress tomorrow.

Cheers,
Dillon

**Comment by Dillon214** [comment]
Hi tare, 

Small update: I ended up finding some success with the second installation method you posted in the installation tutorial after some tinkering with cmdstan. All the commands I had errors with before seem to be working. I'll be closing this issue now, but I have yet to properly use Splotch on my data, and may end up posting another issue in the near future. I want to thank you again for your attentive replies and developing this useful tool!
